DROP TABLE IF EXISTS [Sales]
DROP TABLE IF EXISTS [SalesLine]
DROP TABLE IF EXISTS [SalesOrderNumber]
DROP TABLE IF EXISTS [VendorModel]
DROP TABLE IF EXISTS [VendorBrand]
DROP TABLE IF EXISTS [DimProduct]
DROP TABLE IF EXISTS [DimProductSubcategory]
DROP TABLE IF EXISTS [DimProductCategory]
DROP TABLE IF EXISTS [DimVendor]
DROP TABLE IF EXISTS [DimBrand]
DROP TABLE IF EXISTS [DimModel]
DROP TABLE IF EXISTS [DimPromotion]
DROP TABLE IF EXISTS [DimCurrency]
DROP TABLE IF EXISTS [DimCustomer]
DROP TABLE IF EXISTS [DimDate]
DROP TABLE IF EXISTS [DimGeography]
DROP TABLE IF EXISTS [DimSalesTerritory]


DROP TABLE IF EXISTS [grocery].[Sales]
DROP TABLE IF EXISTS [grocery].[SalesLine]
DROP TABLE IF EXISTS [grocery].[SalesOrderNumber]
DROP TABLE IF EXISTS [grocery].[VendorModel]
DROP TABLE IF EXISTS [grocery].[VendorBrand]
DROP TABLE IF EXISTS [grocery].[DimProduct]
DROP TABLE IF EXISTS [grocery].[DimProductSubcategory]
DROP TABLE IF EXISTS [grocery].[DimProductCategory]
DROP TABLE IF EXISTS [grocery].[DimVendor]
DROP TABLE IF EXISTS [grocery].[DimBrand]
DROP TABLE IF EXISTS [grocery].[DimModel]
DROP TABLE IF EXISTS [grocery].[DimPromotion]
DROP TABLE IF EXISTS [grocery].[DimCurrency]
DROP TABLE IF EXISTS [grocery].[DimCustomer]
DROP TABLE IF EXISTS [grocery].[DimDate]
DROP TABLE IF EXISTS [grocery].[DimGeography]
DROP TABLE IF EXISTS [grocery].[DimSalesTerritory]

