-- Vendor 10-39
-- Brand  10 - 49
INSERT INTO [dbo].[VendorBrand] values (	10	,	49	)
INSERT INTO [dbo].[VendorBrand] values (	11	,	48	)
INSERT INTO [dbo].[VendorBrand] values (	12	,	47	)
INSERT INTO [dbo].[VendorBrand] values (	13	,	46	)
INSERT INTO [dbo].[VendorBrand] values (	14	,	45	)
INSERT INTO [dbo].[VendorBrand] values (	15	,	44	)
INSERT INTO [dbo].[VendorBrand] values (	16	,	43	)
INSERT INTO [dbo].[VendorBrand] values (	17	,	42	)
INSERT INTO [dbo].[VendorBrand] values (	18	,	41	)
INSERT INTO [dbo].[VendorBrand] values (	19	,	40	)
INSERT INTO [dbo].[VendorBrand] values (	20	,	39	)
INSERT INTO [dbo].[VendorBrand] values (	21	,	38	)
INSERT INTO [dbo].[VendorBrand] values (	22	,	37	)
INSERT INTO [dbo].[VendorBrand] values (	23	,	36	)
INSERT INTO [dbo].[VendorBrand] values (	24	,	35	)
INSERT INTO [dbo].[VendorBrand] values (	25	,	34	)
INSERT INTO [dbo].[VendorBrand] values (	26	,	33	)
INSERT INTO [dbo].[VendorBrand] values (	27	,	32	)
INSERT INTO [dbo].[VendorBrand] values (	28	,	31	)
INSERT INTO [dbo].[VendorBrand] values (	29	,	30	)
INSERT INTO [dbo].[VendorBrand] values (  10  , 29  )
INSERT INTO [dbo].[VendorBrand] values (  11  , 28  )
INSERT INTO [dbo].[VendorBrand] values (  12  , 27  )
INSERT INTO [dbo].[VendorBrand] values (  13  , 26  )
INSERT INTO [dbo].[VendorBrand] values (  14  , 25  )
INSERT INTO [dbo].[VendorBrand] values (  15  , 24  )
INSERT INTO [dbo].[VendorBrand] values (  16  , 23  )
INSERT INTO [dbo].[VendorBrand] values (  17  , 22  )
INSERT INTO [dbo].[VendorBrand] values (  18  , 21  )
INSERT INTO [dbo].[VendorBrand] values (  19  , 20  )
INSERT INTO [dbo].[VendorBrand] values (  20  , 19  )
INSERT INTO [dbo].[VendorBrand] values (  21  , 18  )
INSERT INTO [dbo].[VendorBrand] values (  22  , 17  )
INSERT INTO [dbo].[VendorBrand] values (  23  , 16  )
INSERT INTO [dbo].[VendorBrand] values (  24  , 15  )
INSERT INTO [dbo].[VendorBrand] values (  25  , 14  )
INSERT INTO [dbo].[VendorBrand] values (  26  , 13  )
INSERT INTO [dbo].[VendorBrand] values (  27  , 12  )
INSERT INTO [dbo].[VendorBrand] values (  28  , 11  )
INSERT INTO [dbo].[VendorBrand] values (  29  , 10  )



-- Vendor 10 - 39
-- Model  10 - 29
INSERT INTO [dbo].[VendorModel] values (	39,10	)
INSERT INTO [dbo].[VendorModel] values (	38,11	)
INSERT INTO [dbo].[VendorModel] values (	37,12	)
INSERT INTO [dbo].[VendorModel] values (	36,13	)
INSERT INTO [dbo].[VendorModel] values (	35,14	)
INSERT INTO [dbo].[VendorModel] values (	34,15	)
INSERT INTO [dbo].[VendorModel] values (	33,16	)
INSERT INTO [dbo].[VendorModel] values (	32,17	)
INSERT INTO [dbo].[VendorModel] values (	31,18	)
INSERT INTO [dbo].[VendorModel] values (	30,19	)
INSERT INTO [dbo].[VendorModel] values (	29,20	)
INSERT INTO [dbo].[VendorModel] values (	28,21	)
INSERT INTO [dbo].[VendorModel] values (	27,22	)
INSERT INTO [dbo].[VendorModel] values (	26,23	)
INSERT INTO [dbo].[VendorModel] values (	25,24	)
INSERT INTO [dbo].[VendorModel] values (	24,25	)
INSERT INTO [dbo].[VendorModel] values (	23,26	)
INSERT INTO [dbo].[VendorModel] values (	22,27	)
INSERT INTO [dbo].[VendorModel] values (	21,28	)
INSERT INTO [dbo].[VendorModel] values (	20,29	)
INSERT INTO [dbo].[VendorModel] values (	19,10	)
INSERT INTO [dbo].[VendorModel] values (	18,11	)
INSERT INTO [dbo].[VendorModel] values (	17,12	)
INSERT INTO [dbo].[VendorModel] values (	16,13	)
INSERT INTO [dbo].[VendorModel] values (	15,14	)
INSERT INTO [dbo].[VendorModel] values (	14,15	)
INSERT INTO [dbo].[VendorModel] values (	13,16	)
INSERT INTO [dbo].[VendorModel] values (	12,17	)
INSERT INTO [dbo].[VendorModel] values (	11,18	)
INSERT INTO [dbo].[VendorModel] values (	10,19	)
